import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import AuthProvider from "@/context/AuthProvider";
import { Suspense } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Freedom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full relative">
      <AuthProvider>
        <body className={`relative h-full overflow-x-hidden bg-[hsl(109,78%,84%)] ${inter.className}`}>
          <Navbar />

          <main className="pt-14 sm:pt-[5.5rem] relative min-h-screen">
            <div className="fixed -z-20 top-1/2 -left-40 size-40 bg-green-400 rounded-full blur-3xl"></div>
            <div className="fixed -z-20 top-1/4 right-40 size-40 bg-green-400 rounded-full blur-3xl"></div>
            <div className="fixed -z-20 -bottom-1/4 right-40 size-40 bg-green-400 rounded-full blur-3xl"></div>
            <div className="absolute -z-20 top-1/2 -left-20 size-96 bg-green-300 rounded-full"></div>

            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
            <ToastContainer theme="colored" />
          </main>

          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
